In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier 

In [2]:
df = pd.read_csv(r"C://Users//rashi//OneDrive//Desktop//ML//ML FINAL ASSIGNMENTS//Assignment -17//diabetes.csv")
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [4]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [5]:
pd.set_option('display.float_format', '{:.2f}'.format)
df.describe()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin    BMI  \
count       768.00   768.00         768.00         768.00   768.00 768.00   
mean          3.85   120.89          69.11          20.54    79.80  31.99   
std           3.37    31.97          19.36          15.95   115.24   7.88   
min           0.00     0.00           0.00           0.00     0.00   0.00   
25%           1.00    99.00          62.00           0.00     0.00  27.30   
50%           3.00   117.00          72.00          23.00    30.50  32.00   
75%           6.00   140.25          80.00          32.00   127.25  36.60   
max          17.00   199.00         122.00          99.00   846.00  67.10   

       DiabetesPedigreeFunction    Age  Outcome  
count                    768.00 768.00   768.00  
mean                       0.47  33.24     0.35  
std                        0.33  11.76     0.48  
min                        0.08  21.00     0.00  
25%                        0.24  24.00     0.00  
50%                        0.37  29.00     0.00  
75%                        0.63  41.00     1.00  
max                        2.42  81.00     1.00

In [6]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [7]:
feature_columns = [
    'Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 
    'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age'
]

for column in feature_columns:
    print("============================================")
    print(f"{column} ==> Missing zeros : {len(df.loc[df[column] == 0])}")

Pregnancies ==> Missing zeros : 111
Glucose ==> Missing zeros : 5
BloodPressure ==> Missing zeros : 35
SkinThickness ==> Missing zeros : 227
Insulin ==> Missing zeros : 374
BMI ==> Missing zeros : 11
DiabetesPedigreeFunction ==> Missing zeros : 0
Age ==> Missing zeros : 0


In [8]:
from sklearn.impute import SimpleImputer


fill_values = SimpleImputer(missing_values=0, strategy="mean", copy=False)
df[feature_columns] = fill_values.fit_transform(df[feature_columns])

for column in feature_columns:
    print("============================================")
    print(f"{column} ==> Missing zeros : {len(df.loc[df[column] == 0])}")
    

Pregnancies ==> Missing zeros : 0
Glucose ==> Missing zeros : 0
BloodPressure ==> Missing zeros : 0
SkinThickness ==> Missing zeros : 0
Insulin ==> Missing zeros : 0
BMI ==> Missing zeros : 0
DiabetesPedigreeFunction ==> Missing zeros : 0
Age ==> Missing zeros : 0


In [9]:
from sklearn.model_selection import train_test_split


X = df[feature_columns]
y = df.Outcome

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [10]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report


def evaluate(model, X_train, X_test, y_train, y_test):
    y_test_pred = model.predict(X_test)
    y_train_pred = model.predict(X_train)

    print("TRAINIG RESULTS: ")
    clf_report = pd.DataFrame(classification_report(y_train, y_train_pred, output_dict=True))
    print('\n')
    print(f"CONFUSION MATRIX:\n{confusion_matrix(y_train, y_train_pred)}")
    print('\n')
    print(f"ACCURACY SCORE:\n{accuracy_score(y_train, y_train_pred):.4f}")
    print('\n')
    print(f"CLASSIFICATION REPORT:\n{clf_report}")
    print('\n')
    print('\n===============================')
    print('\n')

    print("TESTING RESULTS: ")
    clf_report = pd.DataFrame(classification_report(y_test, y_test_pred, output_dict=True))
    print('\n')
    print(f"CONFUSION MATRIX:\n{confusion_matrix(y_test, y_test_pred)}")
    print('\n')
    print(f"ACCURACY SCORE:\n{accuracy_score(y_test, y_test_pred):.4f}")
    print('\n')
    print(f"CLASSIFICATION REPORT:\n{clf_report}")
    print('\n')

In [14]:
base_model = DecisionTreeClassifier()
bagging_model = BaggingClassifier(base_model, n_estimators=10, random_state=42) 

bagging_model.fit(X_train, y_train)
evaluate(bagging_model, X_train, X_test, y_train, y_test)

TRAINIG RESULTS: 


CONFUSION MATRIX:
[[347   2]
 [  6 182]]


ACCURACY SCORE:
0.9851


CLASSIFICATION REPORT:
               0      1  accuracy  macro avg  weighted avg
precision   0.98   0.99      0.99       0.99          0.99
recall      0.99   0.97      0.99       0.98          0.99
f1-score    0.99   0.98      0.99       0.98          0.99
support   349.00 188.00      0.99     537.00        537.00





TESTING RESULTS: 


CONFUSION MATRIX:
[[123  28]
 [ 33  47]]


ACCURACY SCORE:
0.7359


CLASSIFICATION REPORT:
               0     1  accuracy  macro avg  weighted avg
precision   0.79  0.63      0.74       0.71          0.73
recall      0.81  0.59      0.74       0.70          0.74
f1-score    0.80  0.61      0.74       0.70          0.73
support   151.00 80.00      0.74     231.00        231.00




In [15]:
from sklearn.metrics import accuracy_score


scores = {}

scores = {
    'Bagging Classifier': {
        'Train': accuracy_score(y_train, bagging_model.predict(X_train)),
        'Test': accuracy_score(y_test, bagging_model.predict(X_test)),
    },
}

print(scores)

{'Bagging Classifier': {'Train': 0.9851024208566108, 'Test': 0.7359307359307359}}


In [16]:
from sklearn.ensemble import AdaBoostClassifier

ada_boost_clf = AdaBoostClassifier(n_estimators=30)
ada_boost_clf.fit(X_train, y_train)
evaluate(ada_boost_clf, X_train, X_test, y_train, y_test)


TRAINIG RESULTS: 


CONFUSION MATRIX:
[[310  39]
 [ 51 137]]


ACCURACY SCORE:
0.8324


CLASSIFICATION REPORT:
               0      1  accuracy  macro avg  weighted avg
precision   0.86   0.78      0.83       0.82          0.83
recall      0.89   0.73      0.83       0.81          0.83
f1-score    0.87   0.75      0.83       0.81          0.83
support   349.00 188.00      0.83     537.00        537.00





TESTING RESULTS: 


CONFUSION MATRIX:
[[123  28]
 [ 27  53]]


ACCURACY SCORE:
0.7619


CLASSIFICATION REPORT:
               0     1  accuracy  macro avg  weighted avg
precision   0.82  0.65      0.76       0.74          0.76
recall      0.81  0.66      0.76       0.74          0.76
f1-score    0.82  0.66      0.76       0.74          0.76
support   151.00 80.00      0.76     231.00        231.00




In [17]:
from sklearn.metrics import accuracy_score

scores = {}

scores['AdaBoost'] = {
    'Train': accuracy_score(y_train, ada_boost_clf.predict(X_train)),
    'Test': accuracy_score(y_test, ada_boost_clf.predict(X_test)),
}

print(scores)

{'AdaBoost': {'Train': 0.8324022346368715, 'Test': 0.7619047619047619}}


In [18]:
from sklearn.ensemble import GradientBoostingClassifier
grad_boost_clf = GradientBoostingClassifier(n_estimators=100, random_state=42)
grad_boost_clf.fit(X_train, y_train)
evaluate(grad_boost_clf, X_train, X_test, y_train, y_test)

TRAINIG RESULTS: 


CONFUSION MATRIX:
[[342   7]
 [ 19 169]]


ACCURACY SCORE:
0.9516


CLASSIFICATION REPORT:
               0      1  accuracy  macro avg  weighted avg
precision   0.95   0.96      0.95       0.95          0.95
recall      0.98   0.90      0.95       0.94          0.95
f1-score    0.96   0.93      0.95       0.95          0.95
support   349.00 188.00      0.95     537.00        537.00





TESTING RESULTS: 


CONFUSION MATRIX:
[[116  35]
 [ 26  54]]


ACCURACY SCORE:
0.7359


CLASSIFICATION REPORT:
               0     1  accuracy  macro avg  weighted avg
precision   0.82  0.61      0.74       0.71          0.74
recall      0.77  0.68      0.74       0.72          0.74
f1-score    0.79  0.64      0.74       0.72          0.74
support   151.00 80.00      0.74     231.00        231.00




In [19]:
from sklearn.metrics import accuracy_score

scores = {}

scores['Gradient Boosting'] = {
    'Train': accuracy_score(y_train, grad_boost_clf.predict(X_train)),
    'Test': accuracy_score(y_test, grad_boost_clf.predict(X_test)),
}

print(scores)

{'Gradient Boosting': {'Train': 0.9515828677839852, 'Test': 0.7359307359307359}}
